version: "3.6"
services:
  instuctory_ssr:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: yarn dev
    environment:
      POSTGRES_URI: postgres://saddam:1234@postgres:5432/clone_instructory_db
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: saddam
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clone_instructory_db
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose

